### ISSUE TITLE
Предварительное ревью

### ISSUE THREAD

**Issue by 10Dozen** [rempopo/CO29_Hot_sand.Kunduz#1]
### tSF

- [x] Обновить тСФ до 2.03 (заново сделать инсталл)
- [x] Брифинг: Пункты на английском, это так задумано?
- [x]  Брифинг: в описании говорится про ЗУ-23-2, а во враждебных силах нет
- [x] Брифинг: в описании говорится про мины, но не указано противопехотные или пт, не указано будет ли в наличии сапер и оборудование для разминирования
- [x] Брифинг: `системами электронной блокировки самодельных взрывных устройств` в русских статьях пишут про `системы дистанционной блокировки радиоуправляемых взрывных устройств (блокиратор РВУ)`
- [x] Брифинг: Не указано что такое M1240 - мотоцикл? бтр? гужевая повозка? 
- [x] Брифинг: Технику описывать в формате `(кол-во)х (тип машины) (название) (оружие и оборудование)`, например `1x МРАП M1240 (вооруженный, M2, блокиратор РВУ)`
- [x] Брифинг: в поддержке указать про наличие CCP + FARP
- [x] Брифинг: в "VI. Mission notes:" ненужный "Поверед бай", хотя как работает блокиратор РВУ нужно искать по всему брифингу. Лучше сюда описание работы блокиратор (с дальностью работы, кейбиндами и всем прочим)
- [x] Брифинг: в "V. Command & Signal:"  описаны 2 сквада и 2 канала, а по брифингу 3 сквада, супнета нет (ненужен?)
- [x] Брифинг: не указано что 1'4 - 7 чел. это отделение поддержки (см. http://naf.tacticalshift.ru/mission_making;mission_editor;requirements#%D0%B1%D1%80%D0%B8%D1%84%D0%B8%D0%BD%D0%B3)
- [x] Conditions: Нет условия когда только один обжектив сделали и отступили (`{!alive _x} count [TGT1,TGT2] == 1 && {call fnc_CheckPlayersReturned} `)
- [x] FARP: "tSF_FARP_Composition = ""Land Rover Desert"""; это правильно?

### Dynai
- [x]  Dynai: кол-во INDOOR групп можно делать мешьне, но кол-во ботов в группе может быть больше (т.е. 1-2 группы на зону, в группе по 5-10 юнитов)
- [x]  Dynai: патрули лучше делать маленькими (2-3 бота), но кол-во патрулей увеличить (т.е. 4 группы по 2 будет лучше чем 2 группы по 4); вместо полного рандома можно делать два типа патрулей - `(рандом) + РПГ` и `(рандом) + (рандом легкий/единый пулемет)`

### Gear
- [x] Gear: в GAT и в миссии нет 1'4 Squad leader

### Mission
- [x] Сквады без CBAшного названия (переделать игровые отряды на новом tSF или переименовать вручную сквад лидеров с `1'1 Squad Leader` в `1'1 Squad Leader@1'1` (и соотвественно обновить значения в dzn_gear/GAT и tSF/Support , POM)

**Comment by Comrade333** [comment]
1) ТСФ обновлен
2)Заменены на рус
3)Указал
4)Заменил на "самодельные взрывные устройства"
5)Поменял
6)Уточнил

**Comment by Comrade333** [comment]
7)п

**Comment by Comrade333** [comment]
Все исправлено кроме пункта 12.

**Comment by 10Dozen** [comment]
- [x] Суппорт сквад лучше сделать 1 + 3 (МГ тим) + 3 (АТ тим), во первых более самостоятельные фаертимы, во вторых больше носить могут. Марксменов можно в отдельный сквад или в фаертиму СЛа. Формат, например:
- 1'4 Squad Leader (обычный лоадаут СЛа)
- Marksman (x1-x2)
- MG Team Leader : винтовка (опц. оптика), бинокль/Nite21, патроны
- Machinegunner : пулемет, патроны
- Asst. Machinegunner : винтовка, трипод, остальное патронами
- AT Team Leader : винтовка (опц. оптика), бинокль/Nite21, выстрелы
- AT Specialist : винтовка, гранатомет, выстрелы
- Asst. AT Specialist : винтовка, выстрелы


- [x] 1'6 выше в слоттинге чем 1'4: вырезать, сохранить и вставить 1-6 взад (ctrl + x, ctrl + s, ctrl + v)
- [x] Отметить на карте области где могут находиться противникаи (например маркером NATO - OPFOR - Infantry)
- [x] Позволить размещать CCP вплоть до деревни на Зулу-1 (чтобы не ездить дохуя каждый раз и был смысл "держать мост" по брифингу), например до н.п. Ка-Мала (вплотную или где-то около Г-образного поворота у высоты 11) и/или в районе Shek Ka 
- [x] Для статиков не использован EditorVehicleCrew (чтобы не тупа смотрели в одну сторону, а крутили туда сюда)
- [x] Может заменить куповый М240 на рхсный и треногу для рхс?
- [x] Покрутил брифинг там сям, добавил теги - https://github.com/rempopo/CO27_Hot_sand.Kunduz/pull/3 - мержи если согласен
- [x]  В tSF/Modules/POM роли указаны без `...@1'6`
- [x] Автор TS нинужин, пиши свой никнейм
 - [x] Выключить в Attributes -> Performance -> Enable Dynamic Simulation
- [x] Все еще требую добавить вторую концовку. т.к. TRG_1 и TRG_2 находятся в разных местах и крайней вероятно, что тупа никто не поймет, что ящик около зушки это НЕ кеш, а кеш это ящик в другом месте!!!

**Comment by Comrade333** [comment]
Все исправлено/добавлено.

**Comment by 10Dozen** [comment]
31. MG Team Leader - добавить патроны к пулемету

**Comment by 10Dozen** [comment]
Добавил недостающие исправления в https://github.com/rempopo/CO29_Hot_sand.Kunduz/commit/a03fb394427cba4b74c1dfd8b4df32d1a589c73e
