### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by OneScheer** [rempopo/CO29_Hot_sand.Kunduz#2]
1. Добавить магазины для SCAR в cнаряжение машин.
2. Может добавить расчёты для вражеских миномётов, чтобы ГСО лишний раз не спавнить там всяких ботов. Ну или альтернативно добавить  в замечания для ГСО про спавн расчётов.
3. В 1'4 вместо марксмана добавить Missile Assistant-а, а то ракеты таскать одному тяжело. Предлагаю cнайпера засунуть либо в один из отрядов на место райфлемена, либо отдельно в 1'6
4. Играем за спешл форсез, думаю стоит заменить бинокли на дальномеры Vector. Замени в Kits.sqf в строчке 44 "Binocular" на "ACE_Vector".

**Comment by Comrade333** [comment]
1 и 2 - готово
3 - у минометов стоит бот, которого можно использовать
4 - добавил дальномер

**Comment by OneScheer** [comment]
- [x] почему кит у PL называется kit_111_pl?
- [x] Проверь бинокль у SL и PL, у меня этот Rangefinder не работает.
- [x] У СЛов нет целеуказателя/фонарика на винтовке. Так задумано?

**Comment by Comrade333** [comment]
1)этот кит для добавления лишней штуки в киты, забыл удалить
2)Выдается, лазерка светит.
3)они рандомные, может и не выпасть
